// Relative and extension-qualified so `npm run seed:sql` can import this file
// directly under plain Node, which resolves neither the `@` alias nor an
// extensionless specifier.
import { periodise } from '../../programs/periodise.ts'
import type { Program, ProgramDay } from '../types'

/**
 * The starter programs (§4 Phase 4).
 *
 * Only the specification is written by hand; the 56–84 individual days are
 * generated by `periodise`. Hand-authoring twelve weeks of days would be both
 * tedious and impossible to keep coherent — change the sessions-per-week and
 * every subsequent week has to be rewritten.
 */

interface ProgramSeed extends Omit<Program, 'id' | 'createdAt'> {
  slug: string
}

const SEEDS: ProgramSeed[] = [
  {
    slug: 'return-to-court',
    name: 'Return to Court',
    description:
      'Eight weeks for a player coming back after a long break. Three sessions a week, focused on moving well. It includes an easy week before you feel you need one. Assumes court access.',
    totalWeeks: 8,
    level: 'beginner',
    location: 'court',
    sessionsPerWeek: 3,
    isPublic: true,
    createdBy: null,
  },
  {
    slug: 'rebuild-the-engine',
    name: 'Rebuild the Engine',
    description:
      'Twelve weeks from base fitness to match fitness. Four sessions a week through Base, Build and Sharpen, ending with a taper. The full arc for a club player who wants their legs back by the new season.',
    totalWeeks: 12,
    level: 'intermediate',
    location: 'court',
    sessionsPerWeek: 4,
    isPublic: true,
    createdBy: null,
  },
  {
    slug: 'no-court-comeback',
    name: 'No-Court Comeback',
    description:
      'Ten weeks that need nothing but floor space. Shadow intervals, ladder work and bodyweight circuits. For anyone whose hall is shut, or who only plays once a fortnight.',
    totalWeeks: 10,
    level: 'intermediate',
    location: 'anywhere',
    sessionsPerWeek: 4,
    isPublic: true,
    createdBy: null,
  },
  {
    slug: 'sharpen-for-season',
    name: 'Sharpen for the Season',
    description:
      'Eight hard weeks for a player who already has a base. Five sessions a week, weighted towards speed, reaction and match play. Do not start this one out of shape.',
    totalWeeks: 8,
    level: 'advanced',
    location: 'court',
    sessionsPerWeek: 5,
    isPublic: true,
    createdBy: null,
  },
]

export const SEED_PROGRAMS: Program[] = SEEDS.map((seed) => ({
  ...seed,
  // Locally a program's id is its slug — there is no server to allocate uuids.
  id: seed.slug,
  createdAt: '2026-01-01T00:00:00.000Z',
}))

/** Generates a program's days from its own specification. */
export function daysForProgram(program: Program): ProgramDay[] {
  return periodise({
    totalWeeks: program.totalWeeks,
    sessionsPerWeek: program.sessionsPerWeek,
    level: program.level,
    location: program.location,
  }).map((day) => ({
    id: `${program.id}-w${day.weekNo}d${day.dayNo}`,
    programId: program.id,
    weekNo: day.weekNo,
    dayNo: day.dayNo,
    title: day.title,
    focus: day.focus,
    drillSlugs: day.drillSlugs,
    notes: day.notes,
  }))
}

export function findSeedProgram(slug: string): Program | undefined {
  return SEED_PROGRAMS.find((program) => program.slug === slug)
}
